# Generated by Django 4.2.4 on 2023-10-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='телеграм id'),
        ),
    ]
