# Generated by Django 4.2.4 on 2023-09-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('action', models.CharField(max_length=255)),
                ('is_pleasurable', models.BooleanField(default=False)),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('reward', models.CharField(max_length=255)),
                ('estimated_time', models.PositiveIntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
            ],
        ),
    ]
